### ISSUE TITLE
Bug: Running Angular2 RC1 on Android device give errors, but run perfect on Desktop or iOS devices

### ISSUE THREAD

**Issue by hermanfransen** [angular/angular.js#14698]
I am working on a project with Angular 2.0.0-rc.1 and ran into a bug (I guess). The app runs perfect in the browser on my MacBook, my iPhone and my iPad. But when I run it in a browser on my Android device I get two kinds of errors:

- TypeError: undefined is not a function with reflector.parameters
- Unhandled promise rejection

To reproduce this problem, I random googled plunks running Angular 2.0.0-rc.1 and found the same problems.

All these plunks work perfect without any error in the browser on Chrome 51.0 (64-bit) with OS X 10.11.15

The errors I get in the browser are on Android KitKat 4.4.2; SM-T310 Build/KOT49H running Chrome 40.0.2214.109 Blink-version 537.36 (@189407) Javascript-version v8 3.30.33.16. I connected this device with an USB cable to my OS X machine, enabled the developer options on this Android device and used the `chrome://inspect/#devices` to detect the errors

1. First problem:

http://embed.plnkr.co/TCzW7hZaL46Nz9ZgVWDb/

```
Error: TypeError: undefined is not a function
at ReflectionCapabilities.parameters (https://npmcdn.com/@angular/core@2.0.0-rc.1/src/reflection/reflection_capabilities.js:137:20)
at Reflector.parameters (https://npmcdn.com/@angular/core@2.0.0-rc.1/src/reflection/reflector.js:87:48)
at _dependenciesFor (https://npmcdn.com/@angular/core@2.0.0-rc.1/src/di/reflective_provider.js:178:41)

```
Line 137 of the reflection_capabilities.js: `parameters.fill(undefined);`. This statement is part of the function `ReflectionCapabilities.prototype.parameters`

Same errors with:

https://embed.plnkr.co/Exme2m706sNHtpTGtSVq/
https://embed.plnkr.co/vZ3exjdx2Lo2J2ptSJE2/

2. Second problem:

http://embed.plnkr.co/mztUE3cxHgetbdwn85kV/

```
Unhandled promise rejection Promise {__zone_symbol__then: function, [[PromiseStatus]]: "rejected", [[PromiseValue]]: Error: undefined is not a function
Error loading http://run.plnkr.co/plunks/mztUE3cxHgetbdwn85kV/ap…}__proto__: Promise[[PromiseStatus]]: "rejected"[[PromiseValue]]: Error: undefined is not a function

```
Same errors with:

https://embed.plnkr.co/zbre21tIvfkcZTwpXLNc/
https://embed.plnkr.co/A1Lycbvs4mVCgpc1Lt71/
https://embed.plnkr.co/jsoGHETv5eiygbtkhtb2/
https://embed.plnkr.co/oTLzMZAiUSsuBC4X7Tc2/

**Comment by Narretz** [comment]
Hi, your issue sounds like an issue for Angular2. Please open an issue here: https://github.com/angular/angular/issues

**Comment by hermanfransen** [comment]
Mistake, sorry !!!
