### ISSUE TITLE
Issues seen when upgrading 1.2.9 to 1.5.3

### ISSUE THREAD

**Issue by kaohsi** [angular/angular.js#14440]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

angular.element(document).injector(['ng', 'TSMapp']).invoke is not a function. (In 'angular.element(document).injector(['ng', 'TSMapp']).invoke', 'angular.element(document).injector(['ng', 'TSMapp']).invoke' is undefined)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by gkalpak** [comment]
This doesn't seem to have worked in 1.2.9 either.

You should either do `angular.element(document).injector().invoke` or `angular.injector(['ng', 'TSMapp']).invoke` (this works the same in 1.5.3 as in 1.2.9).

Closing since it works as expected.
:+1: for doing such a big leap forward (from 1.2.9 to 1.5.3 :stuck_out_tongue:)
