### ISSUE TITLE
ngAnimate after update to 1.5 i keep getting tons of TypeError messages.

### ISSUE THREAD

**Issue by konrad-nowicki** [angular/angular.js#13395]
I have updated my project to Angular 1.5 and I started getting this errors on the console.
```
TypeError: realRunner.done is not a function
    at angular-animate.js:2461
    at Scope.$digest (angular.js:16215)
    at Scope.$apply (angular.js:16429)
    at angular.js:18236
    at completeOutstandingRequest (angular.js:5677)
    at angular.js:5954
```
angular#1.5.0-build.4406+sha.7ffb2d3
angular-animate#1.5.0-build.4406+sha.7ffb2d3

**Comment by Narretz** [comment]
It would be good if you could isolate the error and show it in a demo.
A few questions:
1. Did you update from 1.4.x or 1.3.x?
2. Is it from directives such as ng-show / ng-if or are you using $animate directly?

**Comment by frhd** [comment]
Same here. Updated from 1.4.8 to 1.5.0-build.X

Lots of ng-show directives.

**Comment by Narretz** [comment]
Is it possible you have some old version of the angular.js file cached?

**Comment by konrad-nowicki** [comment]
I am using a lot of ng-show and I have updated libs from 1.4.8. 

Below libs I use from bower.json:
```
  "dependencies": {
    "angular": "1.5.0-beta.2",
    "angular-animate": "~1.5.*",
    "angular-aria": "~1.5.*",
    "angular-cookies": "~1.5.*",
    "angular-messages": "~1.5.*",
    "angular-resource": "~1.5.*",
    "angular-sanitize": "~1.5.*",
    "angular-touch": "~1.5.*",
    "angular-material": "~1.0.0-RC5",
    "angular-ui-router": "~0.2.13",
    "angular-translate": "~2.8.1",
    "angular-translate-loader-url": "~2.8.1",
    "angular-material-icons": "~0.6.0",
    "angular-loading-bar": "0.8.0",
    "openlayers": "release-2.13.1",
    "ng-flow": "~2.6.1",
    "angular-local-storage": "~0.2.2",
    "angular-translate-loader-static-files": "~2.8.1"
  },
```

From the debbuger, object does not have done() function
```
animationRunner
AnimateRunner {}
    __proto__:  Object
        cancel: noop()
        complete: noop()
        end: noop()
        pause: noop()
        resume: noop()
        then: (pass, fail)
        __proto__: Object
```

**Comment by Narretz** [comment]
Can someone of you please post a demo to plnkr.co or similar?

**Comment by blazingAvatar** [comment]
Experiencing same issue with 1.5
demo - http://embed.plnkr.co/cLGKZB/

**Comment by Narretz** [comment]
@blazingAvatar The beta versions of angular and angular-animate must match: http://plnkr.co/edit/EGkylQ?p=preview

**Comment by konrad-nowicki** [comment]
I have wrongly assumed that this will resolve to the same version.
    "angular": "1.5.0-beta.2",
    "angular-animate": "~1.5.*"

Thank you for your help.

**Comment by blazingAvatar** [comment]
Thanks for the help.

**Comment by Narretz** [comment]
Looks like this is resolved then!

**Comment by nkimaina** [comment]
I got this error when my version of angular was 1.4.7 and version of angular-animate being 1.5.4. Switching the version of angular-animate to 1.4.7 did the trick

**Comment by crucialfelix** [comment]
Even angular 1.4.4 and angular-animate 1.4.10 will cause this

be careful to lock your dependencies. I had 

    "angular-animate": "~1.4.4",

and got 1.4.10 installed

lock it down:

    "angular-animate": "^1.4.4",

**Comment by gkalpak** [comment]
@crucialfelix, note that you should always have matching version of core angular and external angular modules (e.g. angular-animate). Non-matching versions are not guaranteed to work together.

**Comment by crucialfelix** [comment]
Yes thanks, I know that. But because I had used `~1.4.4` rather than `^1.4.4` I unexpectedly got a 1.4.10 installed. I kept looking at the package file to make sure they were matching versions and eventually checked the npm-shrinkwrap and npm list and realized they weren't the same.

**Comment by mariohmol** [comment]
I'm using it with meteor and getting same error.

Here are my versions

`"dependencies": {
    "angular": "^1.5.5",
    "angular-animate": "^1.5.5",
    "angular-aria": "^1.5.5",
    "angular-component": "^0.1.0",
    "angular-material": "^1.0.8",
    "angular-messages": "^1.5.5",
    "angular-meteor": "^1.3.10",
    "angular-mocks": "^1.5.5",
    "angular-route": "^1.5.5",
    "angular-sanitize": "^1.5.5",
    "angular-ui-router": "^0.3.0",
    "meteor-node-stubs": "~0.2.0"
  }`

**Comment by mariohmol** [comment]
Oopps.. i'm new on meteor so package.json is not same version that were inside meteor (i couldnt get anyway).
 Running this command i could get it work:

meteor update angular:angular

And it  upgraded from 1.4.8 to 1.5.3_1

Thanks to:

* http://stackoverflow.com/questions/37101456/console-errors-with-angular-material-and-meteor

**Comment by 1mike12** [comment]
^ solved my problem too. Needed to update my 1.4.8 to 1.5

**Comment by Yash-777** [comment]
same problem is resolved by using `angular`, `angular-animate` - [`1.5.0-beta.2`](https://cdnjs.com/libraries/angular.js/1.5.0-beta.2) version
