### PR TITLE
fix($animate): do not get affected by custom, enumerable properties on `Object.prototype`

### LINKED ISSUE #14804: 'list.filter is not a function' in filterFromRegistry in animateQueue.js in 1.5.5+
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
error: `list.filter is not a function`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
call `$animate.off(element);`

**What is the expected behavior?**
works in 1.5.3 and before

**What is the motivation / use case for changing the behavior?**
bug introduced in 1.5.5 when `filterFromRegistry` was changed from a being local function of `$animate.off` method in `animateQueue.js`

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
1.5.5 and later, all browsers and OSes.  Works with 1.5.3 and before.  Still broken in `master` branch.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
[function filterFromRegistry(list, matchContainer, matchCallback)](https://github.com/angular/angular.js/blob/master/src/ngAnimate/animateQueue.js#L204) takes three parameters, but is called with two only in [callbackRegistry[eventType] = filterFromRegistry(callbackRegistry[eventType], container);](https://github.com/angular/angular.js/blob/master/src/ngAnimate/animateQueue.js#L247) causing `TypeError` `list.filter is not a function`

### PR DESCRIPTION
**Pull request by gkalpak**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Regression fix.

**What is the current behavior? (You can also link to an open issue here)**
Putting custom, enumerable properties on `Object.prototype`, can break animations.
See #14804.

**What is the new behavior (if this is a feature change)?**
Animations are not affected by custom, enumerable properties on `Object.prototype`.

**Does this PR introduce a breaking change?**
No.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:
Fixes #14804.

### CODE REVIEW

**Comment by Narretz** [comment]
LGTM
