### ISSUE TITLE
angular-animate.js jqLiteAddClass error (1.4.0-rc.0)

### ISSUE THREAD

**Issue by demisx** [angular/angular.js#11550]
Since upgrading to v1.4.0-rc.0, I am seeing this error in the console log (see below). FYI, I am not using any special animation, besides what angular material provides.

```js
TypeError: undefined is not a function
    at jqLiteAddClass (angular.js:2828)
    at Function.$get.extend.addClass (angular.js:3468)
    at angular-animate.js:100
    at forEach (angular.js:332)
    at $$addClass (angular-animate.js:99)
    at options (angular-animate.js:113)
    at close (angular-animate.js:2192)
    at queueAnimation (angular-animate.js:2043)
    at Object.$$AnimateQueueProvider.$get.push (angular-animate.js:1943)
    at Object.$AnimateProvider.$get.leave (angular.js:5017)
```

**Comment by matsko** [comment]
Any chance you get can get a plnkr link? Something super basic. My guess is that `cssClasses` is being passed in as an array instead of a string.

**Comment by matsko** [comment]
Mind providing the version of Material that you're using?

**Comment by matsko** [comment]
As well as the template code that's causing the issue. Looks like there may be a parameter for `$animate.leave` that is getting passed in somewhere within material that is the wrong type.

**Comment by demisx** [comment]
@matsko Sorry for the delayed reply. A little swamped here. I am using angular animate 0.8.3 stable release. I will try to put together a plunker shortly.

**Comment by demisx** [comment]
I am having difficulties isolating this issue in a plunker. Posting a screenshot of the stack just in case it helps. 

![11550-animate-error](https://cloud.githubusercontent.com/assets/4452412/7147971/dce3cb56-e2b3-11e4-9ffd-ef7e597eabe3.png)

**Comment by levbrie** [comment]
It looks like angular-animate is expecting that when `$$addClass` is called, the third parameter passed in will be the element's class name (or names):

![screenshot 2015-04-18 17 14 25](https://cloud.githubusercontent.com/assets/1441307/7217288/6037ef36-e5ee-11e4-9741-f1d7b34fb13b.png)

When it's called on line 115, however, it's using `options.addClass`, `options.addClass` is instead a function:

![screenshot 2015-04-18 17 08 53](https://cloud.githubusercontent.com/assets/1441307/7217289/a1844084-e5ee-11e4-8ff3-08b09b669a13.png)

These options are first set by angular in the `$animate#leave` function:

![screenshot 2015-04-18 17 27 54](https://cloud.githubusercontent.com/assets/1441307/7217307/7131614e-e5f0-11e4-80b8-5d2067090909.png)

which angular-material calls when attempting to toggle the sidenav and attach/detach listeners (at least in my case):

![screenshot 2015-04-18 17 27 25](https://cloud.githubusercontent.com/assets/1441307/7217312/b91c95fa-e5f0-11e4-881a-665a9028d186.png)

Anyway, the problem seems to be that angular-material is passing in the parent element to a function that's expecting to receive an options object, although I'm not sure if this is (a) intentional and options can in fact be represented by an element but something with addClass has recently changed (b) unintentional and angular-material is no longer making a correct call, or (c) unintentional on the part of angular-animate, which should be preparing this element/options object in either the `queueAnimation` or `prepareAnimationOptions` functions.  Anyway, hope that helps.

**Comment by oliverzy** [comment]
This one has been fixed in latest master on anuglar-material. It's not a angular-animate bug.

**Comment by Narretz** [comment]
Can you confirm that @demisx?

**Comment by matsko** [comment]
I can confirm that this was a pure material bug, however, at the time of this issue the latest version was not released yet. Angular-Material RC1 should've released the fix with it, if not then RC2 should definitely have it when it is released later today or tomorrow.

**Comment by demisx** [comment]
Yes, I can confirm that this particular bug appears to be gone from 0.9.0-rc1 release. I do not see the error message anymore. Thank you guys for taking care of it so fast!
