### ISSUE TITLE
getting TypeError: modelCtrl.$$initGetterSetters is not a function after updating from 1.5.8 to 1.6.4

### ISSUE THREAD

**Issue by nehagupta13688** [angular/angular.js#15936]
Hello Guys, I am upgrading my angular project from 1.5.8 to 1.6.4 and after updating the project, when I run the application I am getting following exceptions on the console. Not sure why it is happening.

angular.js:14525 TypeError: modelCtrl.$$initGetterSetters is not a function
at Object.ngModelPreLink (angular.js:29213)
at angular.js:1346
at invokeLinkFn (angular.js:10426)
at nodeLinkFn (angular.js:9792)
at compositeLinkFn (angular.js:9055)
at compositeLinkFn (angular.js:9058)
at compositeLinkFn (angular.js:9058)
at publicLinkFn (angular.js:8920)
at Object.link (angular.js:27844)
at angular.js:1346 ""

TypeError: ctrl.$isEmpty is not a function
at Array. (angular.js:24772)
at ngModelWatch (angular.js:28954)
at Scope.$digest (angular.js:17991)
at Scope.$apply (angular.js:18269)
at done (angular.js:12387)
at completeRequest (angular.js:12613)
at XMLHttpRequest.requestLoaded (angular.js:12541)
at XMLHttpRequest.nrWrapper (localhost/:15)

**Comment by frederikprijck** [comment]
`modelCtrl.$$initGetterSetters is not a function`
This looks like there's an angularjs library which is not on 1.6.x yet. Possible angular.js itself.
Could you verify that all angularjs libraries (in bower or npm) are on the same version, being the one you want to upgrade to (1.6.4) ?

**Comment by nehagupta13688** [comment]
/**
 * @license AngularJS v1.6.4
 * (c) 2010-2017 Google, Inc. http://angularjs.org
 * License: MIT
 */

I see this inside angular.js

But when I opened the angular.js file, I found so many compilation issues with that file.

![image](https://cloud.githubusercontent.com/assets/28012870/25397879/e067b72c-29b7-11e7-8596-6114b792951e.png)

**Comment by Narretz** [comment]
This is a doc block, this has nothing to do with your problem.

The line numbers in your error match 1.6.4, but I have no idea why this error would be called. Maybe your file is corrupted or the modelController has been modified by a different module (e.g decorator).

**Comment by nehagupta13688** [comment]
You are right. modelController was modified by a decorator. 

     // Workaround for bug #1404
      // https://github.com/angular/angular.js/issues/1404
      // Source: http://plnkr.co/edit/hSMzWC?p=preview

    /*  $provide.decorator('ngModelDirective', ['$delegate', function ($delegate) {
        var ngModel = $delegate[0], controller = ngModel.controller;
        ngModel.controller = ['$scope', '$element', '$attrs', '$injector', function (scope, element, attrs, $injector) {
          var $interpolate = $injector.get('$interpolate');
          attrs.$set('name', $interpolate(attrs.name || '')(scope));
          $injector.invoke(controller, this, {
            '$scope': scope,
            '$element': element,
            '$attrs': attrs
          });
        }];
        return $delegate;
      }]);*/
   /*   $provide.decorator('formDirective', ['$delegate', function ($delegate) {
        var form = $delegate[0], controller = form.controller;
        form.controller = ['$scope', '$element', '$attrs', '$injector', function (scope, element, attrs, $injector) {
          var $interpolate = $injector.get('$interpolate');
          attrs.$set('name', $interpolate(attrs.name || attrs.ngForm || '')(scope));
          $injector.invoke(controller, this, {
            '$scope': scope,
            '$element': element,
            '$attrs': attrs
          });
        }];
        return $delegate;
      }]);*/

I am not getting those wired exceptions anymore after commenting that stuff. Thanks Guys for your support

**Comment by Narretz** [comment]
Ok, closing then. Btw the issue referenced in the decorator has been fixed for a long time
