### ISSUE TITLE
AngularJS throws error after 1.4.0 update

### ISSUE THREAD

**Issue by mattiacorvaglia** [angular/angular.js#12011]
After update AngularJS to 1.4.0 (with `bower update` command) I get this error in the console:
`Uncaught TypeError: $browser.addPollFn is not a function (angular.js:4390)`

```
  ////////////////////////////////////
  // internal Injector
  ////////////////////////////////////

  function createInternalInjector(cache, factory) {

    function getService(serviceName, caller) {
      if (cache.hasOwnProperty(serviceName)) {
        if (cache[serviceName] === INSTANTIATING) {
          throw $injectorMinErr('cdep', 'Circular dependency found: {0}',
                    serviceName + ' <- ' + path.join(' <- '));
        }
        return cache[serviceName];
      } else {
        try {
          path.unshift(serviceName);
          cache[serviceName] = INSTANTIATING;
          return cache[serviceName] = factory(serviceName, caller);
        } catch (err) {
          if (cache[serviceName] === INSTANTIATING) {
            delete cache[serviceName];
          }
          throw err; <------------------------------------------------------------------------
        } finally {
          path.shift();
        }
      }
    }
```

**Comment by mattiacorvaglia** [comment]
I solved updating also `angular-cookies` and `angular-resource` modules to 1.4.0
