### ISSUE TITLE
ng-click function not receiving databinding value

### ISSUE THREAD

**Issue by gharig** [angular/angular.js#14255]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
Possible bug.

I upgraded to angular 1.5.1, version 1.4.9 does not produce this error

**What is the current behavior?**

I receive the following error: 

angular.js:13283 Error: Could not resolve '{{m.ref}}' from state 'main'
    at Object.transitionTo (angular-ui-router.js:3179)
    at Object.go (angular-ui-router.js:3107)
    at Header.goTo (header.js:37)
    at fn (eval at <anonymous> (angular.js:14127), <anonymous>:4:297)
    at expensiveCheckFn (angular.js:15140)
    at callback (angular.js:24663)
    at Scope.$eval (angular.js:16884)
    at Scope.$apply (angular.js:16984)
    at HTMLAnchorElement.<anonymous> (angular.js:24668)
    at defaultHandlerWrapper (angular.js:3417)

this  works in version 1.4.9. 
I believe that the ng-click listed in the header file below is not receiving the value from the controller and that the error " Could not resolve '{{m.ref}}'  " 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

HEADER.HTML FILE..................................

<nav ng-controller="HeaderCtrl as vm" class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">

        
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" aria-expanded="false" ng-click="vm.toggleMenu()">
                
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Ongo</a>
        </div>

        
        
        <div class="collapse navbar-collapse" id="menu-1" ng-class="vm.showMenu && 'in'">
            <ul class="nav navbar-nav">
                <li ng-repeat="m in vm.menus">
                    <a ng-hide="vm.displayMenu({{m.hideOnAuth}})" ng-click="vm.goTo('{{m.ref}}')">{{m.name}}</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

CONTROLLER............................................

(function (ng) {
    'use strict';
    
    ng.module('app')
      .controller('HeaderCtrl', Header);
      
    Header.$inject = ['$auth', '$state', 'headerMenu'];

    function Header($auth, $state, headerMenu) {

        var vm = this;

        vm.toggleMenu = toggleMenu;
        vm.goTo = goTo;
        vm.displayMenu = displayMenu;
        vm.showMenu = false;
        vm.menus = headerMenu.get();
        
        //Load the menu items from the factory headerMenu
        //vm.menus = 
        

        function toggleMenu() {
            vm.showMenu = (vm.showMenu) ? false : true;
        }      
            
        function goTo(value) {

            if (value !== undefined) {
                $state.go(value);
            }
            toggleMenu();
        }

        function displayMenu(hideOnAuth) {
            
            if (hideOnAuth === undefined) {
                return false;
            }
            
            var A = $auth.isAuthenticated() ? 1 : 0;
            var B = hideOnAuth ? 1 : 0;
            if (hideOnAuth === true) {
                var p = Boolean(A & B);
                return p;
            }
            else {
                var q = Boolean(A ^ B);
                return !q;
            }
        }

    }

})(window.angular);

HEADER SERVICE........................................................
(function (ng) {
    'use strict';
    
    ng.module('app').factory('headerMenu', headerMenu);
    
    
    
    function headerMenu() {
        
        var menu = {};
        menu.list = [];
         

        // Public API here
        var factory = {
            get: getMenu,
            add: addMenu,
            clear: clearMenu
        };
        
        clearMenu();
        
        addMenu({ name: "How it works", ref: "howItWorks" });
        addMenu({ name: "Happenings", ref: "" });
        addMenu({ name: "Contact", ref: "" });
        addMenu({ name: "Complain", ref: "complain" });
        addMenu({ name: "Chicken Talk", ref: "" });
        addMenu({ name: "Login", ref: "login", hideOnAuth: true });
        addMenu({ name: "Logout", ref: "logout", hideOnAuth: false });
        addMenu({ name: "Join", ref: "register", hideOnAuth: true });
        addMenu({ name: "Profile", ref: "profile", hideOnAuth: false });
        
        //api functions
        function getMenu() {
            return menu.list;
        }

        function addMenu(menuItem) {
            //{ name: "Profile", ref: "profile", hideOnAuth: false }
            menu.list.push(menuItem);
        }
 
        function clearMenu() {
            while (menu.list.length > 0) {
                menu.list.pop();
            }
        }        
       
        return factory;
    }

})(window.angular);

**What is the expected behavior?**
i expect not to see an error.

**What is the motivation / use case for changing the behavior?**

upgrade to 1.5.1

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by Narretz** [comment]
Can you please create a demo of that behavior and put it into a plnkr or similar?
Also, I see you are using ui-router. It would make sense to also open an issue in their repo, and also try to reproduce the problem without it,

**Comment by gharig** [comment]
Hi Narretz,
I will try to put something together in the next day or two and will let you know.

**Comment by gharig** [comment]
Hi Narretz,

Well it looks as if its not a bug, but a miss understanding of how I believe ng-click works.

The following snippet of code has worked since version 1.2.

<li ng-repeat="m in vm.menus">
   <a 
       ng-hide="vm.displayMenu({{m.hideOnAuth}})" 
       ng-click="vm.goTo('{{m.ref}}')">{{m.name}}
   </a>
 </li>

And I have been keeping up with the version changes up to 1.4.9.  And when I switched to version 1.5.1 it stooped working, so of course my first thought is that this is some small bug. But as it turns out all I had to do was remove the {{}} from the function and the single quote.


<li ng-repeat="m in vm.menus">
   <a 
       ng-hide="vm.displayMenu(m.hideOnAuth)" 
       ng-click="vm.goTo(m.ref)">{{m.name}}
   </a>
 </li>


Thanks For your help.
George
