### ISSUE TITLE
$interpolate(true)({}) throws error

### ISSUE THREAD

**Issue by pabloes** [angular/angular.js#15292]
**Do you want to request a *feature* or report a *bug*?**
bug or breaking change.

**What is the current behavior?**
if we inject $interpolate and use it with a value that is not a String, an error is thrown because replace only exists in String.prototype.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a $interpolate(true)({});

**What is the expected behavior?**
If the behaviour is ok, at least throw a concise error and test it in the spec.
Expected behaviour is the same as previous version, 1.4.9 at least. In this version while (index < textLength) avoided executing text.replace, the result is an empty string.

**What is the motivation / use case for changing the behavior?**
It's a breaking change if someone used $interpolate service calling it with a first parameter that is not a string.
  TypeError: text.replace is not a function
            at unescapeText (webpack:///./~/angular/angular.js?:12183:19)
            at $interpolate (webpack:///./~/angular/angular.js?:12336:31)

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
It worked with angular 1.4.9; It does not work with angular 1.5.8

**Comment by Narretz** [comment]
@jbedard Seems like this is the result of https://github.com/angular/angular.js/commit/cf83b4f445d3a1fc18fc140e65e670754401d50b Would you mind taking a look?

**Comment by jbedard** [comment]
It didn't really handle this before cf83b4f either. It might not have crashed but it didn't detect it and throw any proper error message.

Is this really worth fixing? I don't like the idea of detecting every possible programmer error...

**Comment by Narretz** [comment]
That is a good point, actually. The function is documented as only taking strings. @pabloes What is your use case for passing a boolean to interpolate? Or in what circumstance does it happen?

**Comment by pabloes** [comment]
I'm involved in a migration from angular 1.4.9 to ~1.5.8

In my case we have a function that can receive an string or a boolean, and I execute first the interpolation and afterwards checks if the parameter is a boolean. In previous version no error was thrown and the execution was going forward.

For me is really easy to solve, just check the parameter and if it's not a string avoid using $interpolate, or a try catch; but I was just thinking if you want to do something here to avoid the error or to throw a precise error. 

Anyway it's true that the documentation says that first parameter must be a string.

**Comment by Narretz** [comment]
In that case, I think we should leave it as is. The change has been in the stable version for almost 6 months and this is the first issue about it. If more poeple encounter this problem, we can reconsider a different behavior.
