### ISSUE TITLE
Breaking changes ngSanitize 1.6.3

### ISSUE THREAD

**Issue by vikkio88** [angular/angular.js#15791]
**bug**
the info added in the last line of this file https://github.com/angular/angular.js/blob/master/src/ngSanitize/sanitize.js#L552 it does not work using angular 1.5.1

**What is the current behavior?**
Getting an error
```
Uncaught TypeError: angular.module(...).provider(...).info is not a function
```

**What is the expected behavior?**
I expect it to work with the angular version 1.5.1 as it was doing untill angular-sanitize 1.6.2

**What is the motivation / use case for changing the behavior?**
info not present in angular1.5.* (?)

**Which versions of AngularJS, and which browser / OS are affected by this issue? Did this work in previous versions of AngularJS? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
1.5.1 (all the production env is to this angular version)

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
to fix just remove the ```.info(``` bit at the end and it will work just fine
to temp fix I locked the version to 1.6.2

**Comment by eCorke** [comment]
Same goes for ngCookies, thanks ;-)

**Comment by frederikprijck** [comment]
You'll need to upgrade all other libraries to `1.6.3` aswell.

Afaik, AngularJS isn't supposed to be used with different versions of each module.

**Comment by vikkio88** [comment]
@frederikprijck yeah I guess so, unfortunatelly I can't decide the version of angular to use in production I just wanted to report it in case someone else would find it useful

**Comment by petebacondarwin** [comment]
We do not support running core AngularJS that are at different versions. Can you explain why you would upgrade `angular.js` to 1.6.x but leave `angular-sanitize.js` at 1.5.x?

**Comment by frederikprijck** [comment]
Other way around I guess @petebacondarwin  :D

**Comment by vikkio88** [comment]
@petebacondarwin basically was accidentaly supported till 1.6.3, just reporting this in case someone will need it and will face the same issue

**Comment by vikkio88** [comment]
not a bug

**Comment by rev-robert** [comment]
I am getting the error and my calls to all the libraries are the same version.

	
	<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular-route.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular-animate.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular-resource.js"></script>

Respectfully,
Robert

**Comment by vikkio88** [comment]
it is not a bug, you should lock the dependencies

**Comment by rev-robert** [comment]
Dear Vikki,


How does one do that?


Respectfully,

Robert

**Comment by vikkio88** [comment]
My Dearest @rev-robert,
I hope you are having a good day, 
I see that you are using the CDN libs, you just use the previous version 1.5.x would do, unless you are not using ```package.json```, in that case you will need to hardcode the version number in there.

Kind Regards,
Your Sincerely Vikki**o**

**Comment by sajidsidhu** [comment]
just use same version of (angular.min.js) and (angular-sanitize.min.js)
it will fixed 100% ;)
