### ISSUE TITLE
manual bootstrap and ngAnimate

### ISSUE THREAD

**Issue by MrWook** [angular/angular.js#16020]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**
NgAnimate throws this error:
> $$animateJs is not a function

**Expected / new behavior:**
NgAnimate don't throw an error.

**Minimal reproduction of the problem with instructions:**

1. Fetch data from the Server before angular is bootstraped (or a timeout)
2. Manual bootstrap the application
3. See same error in the console which can be prevented if you set `$animate.enabled(true);` in the config block
4. Have a hyperlink element like `<a href="site/test">Click me</a>` ('site/test' is in the same application just a different view for ng-view)
5. Press the hyperlink with the middle mouse button
6. `$$animateJs` is missing in the new tab for `$$AnimateJsDriverProvider`

**Angular version:** 1.6.4

**Browser:** 
Could only be produced in Chrome 58.0.3029.110 (64-bit), works fine in IE 11.0.42 and Firefox 53.0.3

**Anything else:**
Like i said in "6." `$$animateJs` isn't just missing at the beginning. It's missing till you refresh the application on the new tab

**Comment by frederikprijck** [comment]
Out of curiosity, are you using something like ocLazyLoad or anything to lazy load certain things ?

**Comment by MrWook** [comment]
Hello @frederikprijck,

Yes i'm using ocLazyLoad and thanks for both of the issues, didn't find the first one here.
So it's not a problem from angular but from ocLazyLoad. The moment i injected `$$animateJs` as a dependency for the ocLazyLoad function it worked.
Also `$animate.enabled(true);` is not required anymore if it is injected in the ocLazyLoad function.

But weird that this error only occured in Chrome.

Thanks again for your time, i wasted hours into this.
