### ISSUE TITLE
OrderBy does not work with trackby $index

### ISSUE THREAD

**Issue by Tallyb** [angular/angular.js#14253]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

Bug - breaking change from 1.4.x

**What is the current behavior?**

Console error: 
angular.min.js:114 Error: [orderBy:notarray] http://errors.angularjs.org/1.5.0/orderBy/notarray?p0=0
    at Error (native)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.min.js:6:416
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.min.js:166:459
    at fn (eval at <anonymous> (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.min.js:223:455), <anonymous>:4:179)
    at p (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.min.js:291:394)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.min.js:292:146
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.min.js:137:292
    at m.$digest (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.min.js:138:399)
    at m.$apply (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.min.js:141:341)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.min.js:21:44

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

see attached plunker: http://plnkr.co/edit/0CrExF0XRLNNqMlclJa0?p=preview

**What is the expected behavior?**

Show the items as per the requested order

**What is the motivation / use case for changing the behavior?**

worked in 1.4.x 

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

Angular 1.5.0. Chrome , FF on Windows. 

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by Tallyb** [comment]
sorry - apparetnly it is solved. 
http://stackoverflow.com/questions/34175783/filternotarray-expected-array-but-received-0
