### ISSUE TITLE
using ngMockE2E to test live http requests is throwing error in the latest 1.5.7 version but it is working in 1.4.0-rc.2 version

### ISSUE THREAD

**Issue by gondar00** [angular/angular.js#14909]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
 BUG

**What is the current behavior?**
I am trying to follow this blog post 
http://www.bradoncode.com/blog/2015/06/16/unit-test-http-ngmock-passthrough/

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

http://plnkr.co/edit/K4wtX5grhdiQQ8CkJIyR - works fine (AngularJS version 1.4.0-rc.2)
http://plnkr.co/edit/Ku2thXHgUgeNzcg2LC5d - does not work .. (AngularJS version 1.5.7)

**What is the expected behavior?**
Should not throw an error 
TypeError: $controller is not a function or Error: [$injector:modulerr] Failed to instantiate module ngMock due to:
Error: [$injector:unpr] Unknown provider: $$asyncCallbackProvider

**What is the motivation / use case for changing the behavior?**
The different versions of angularjs

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

it is working with (AngularJS version 1.4.0-rc.2) but not with the latest stable build

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by gkalpak** [comment]
That post is out-dated (refers to older Angular versions) and messes with internals, so it runs the risk of breaking at any point (as happened here). You can apparently fix it by removing the bits about `$$asyncCallbacks` (which has been removed from Angular): [Updated plnkr][1]

Yet, since ff0395f, it is possible (even if not recommended) to use `ngMockE2E` alongside `ngMock`, so you might be able to spare the trouble: [Demo][2]

--
Closing, since everything works as expcted.

[1]: http://plnkr.co/edit/qvBxDX1duVn9JZlYYfWL?p=preview
[2]: http://plnkr.co/edit/L1VPxahTPHJACajkthfK?p=preview
