### ISSUE TITLE
'list.filter is not a function' in filterFromRegistry in animateQueue.js in 1.5.5+

### ISSUE THREAD

**Issue by kyrylkov** [angular/angular.js#14804]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
error: `list.filter is not a function`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
call `$animate.off(element);`

**What is the expected behavior?**
works in 1.5.3 and before

**What is the motivation / use case for changing the behavior?**
bug introduced in 1.5.5 when `filterFromRegistry` was changed from a being local function of `$animate.off` method in `animateQueue.js`

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
1.5.5 and later, all browsers and OSes.  Works with 1.5.3 and before.  Still broken in `master` branch.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
[function filterFromRegistry(list, matchContainer, matchCallback)](https://github.com/angular/angular.js/blob/master/src/ngAnimate/animateQueue.js#L204) takes three parameters, but is called with two only in [callbackRegistry[eventType] = filterFromRegistry(callbackRegistry[eventType], container);](https://github.com/angular/angular.js/blob/master/src/ngAnimate/animateQueue.js#L247) causing `TypeError` `list.filter is not a function`

**Comment by gkalpak** [comment]
I don't see why this would be a problem. Omitting the third parameter (`callback`), doesn't explain the `list.filter is not a function` error. Could you create a demo (e.g. using CodePen, Plnkr, etc) ?

**Comment by kyrylkov** [comment]
Broken by https://github.com/angular/angular.js/commit/ea4120bf3524c270cebbf3e4dd0ba31552de6f1f

**Comment by gkalpak** [comment]
This could happen under some circumstances if `callbackRegistry[eventType] === null`.
We should probably short-circuit this case in `filterFromRegistry`:

```js
function filterFromRegistry(list, matchContainer, matchCallback) {
  if (!list) return list;
  ...
}
```

**Comment by kyrylkov** [comment]
@gkalpak @Narretz 

```
function filterFromRegistry(list, matchContainer, matchCallback) {
  console.log(typeof list);
  ...
}
```
shows `function`

**Comment by kyrylkov** [comment]
So we fixed the code by removing `allFalse` from `Object.prototype`. 

However it did work in 1.5.3 and before and was broken by https://github.com/angular/angular.js/commit/ea4120bf3524c270cebbf3e4dd0ba31552de6f1f

**Comment by Narretz** [comment]
@gkalpak Since you are assigned, do you want to write a fix for this?

**Comment by gkalpak** [comment]
@Narretz, as far as I understand from @kyrylkov's comments, the reason this breaks is because they added custom, enumerable properties on `Object.prototype`. If people do this, lots of other stuff could break. Do you still think we should "fix" this?

We could use `Object.keys(...).forEach(...)` instead of `for ... in ...` in [animateQueue.js#L246][1].

[1]: https://github.com/angular/angular.js/blob/d406a15e8cfd0d57c91147c46994f532dc458021/src/ngAnimate/animateQueue.js#L246

**Comment by Narretz** [comment]
Could we also use callbackRegistry = createMap()?

**Comment by gkalpak** [comment]
Probably :smiley:

**Comment by hariharasudhankm** [comment]
is this on master yet?

**Comment by Narretz** [comment]
Yes
